"""Add unique constraint to sacco_metrics

Revision ID: 1d8f38e9ab97
Revises: cd05ba03f21a
Create Date: 2025-05-22 20:40:43.183723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8f38e9ab97'
down_revision: Union[str, None] = 'cd05ba03f21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_doc_year_uc', 'sacco_metrics', ['document_id', 'year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_doc_year_uc', 'sacco_metrics', type_='unique')
    # ### end Alembic commands ###
